### ISSUE TITLE
Issue with TV 7.3.1 + Typo3 9.5.11 when using multiple languages

### ISSUE THREAD

**Issue by ymauray** [pluspol-interactive/templavoilaplus#266] opened 2019-11-27 15:47 UTC
Hello.

In typo3 9.5.11, I created a page in french - my default language -, associated a Template Object, and then created an english version of the page. The page works fine in french, but when I switch to english, I get an error : 

> TemplaVoila Plus ERROR:
> 
> Couldn't find a Data Structure set for table/row "pages:1".
> Please select a Data Structure and Template Object first.

I don't understand if this is an error on my part, of a problem with TV.

Do I have to change the `Language` property of the Template Object to `[All]` ? Because I can't do that either : TV tries to set `sys_language_uid` in `tx_templavoilaplus_tmplobj` to `-1` but the column is `UNSIGNED`.

Any bit of information may help. Thanks !

**Comment by opi99** [comment] 2019-12-04 12:35
Hi,

can you check if this error also happens, if you use latest git source from the 7.3.x branch?

**Comment by ymauray** [comment] 2019-12-04 13:04
I'd love to but that gives me a lot of errors. I did `git clone https://github.com/pluspol-interactive/templavoilaplus.git` in the `typo3conf/ext` folder. Is there something else I should do, besides running the upgrade script and nuking `typo3temp` ?

**Comment by opi99** [comment] 2019-12-04 14:40
Please do not use the master branch, you need to switch into the 7.3.x branch (`git checkout 7.3.x` after cloning).

**Comment by ymauray** [comment] 2019-12-04 15:02
😁 silly me.... ok, so the latest 7.3.x does not generate errors, however, I get the same result : 
![image](https://user-images.githubusercontent.com/2527227/70153269-f5ab8280-16ae-11ea-9447-a22b66412160.png)
What information can I give you to help ? I can export data from the database if you need. 
Typo3 9.5.11 using symlinks and not composer, php 7.3.12, MySQL 5.7.27, FreeBSD 12.0
Site configured to use 4 languages, using Typo3 9 native multilang system.
Default language works fine, any other languages doesn't.
Thanks !

**Comment by ymauray** [comment] 2019-12-04 15:21
Ah ! I found it. 
I need to set the DS for each version of the page. Translated pages don't inherit the DS from the main language.
Is that an expected behavior ? Do you want me to open another issue for that ?
I guess this issue can be closed now.

**Comment by opi99** [comment] 2019-12-05 12:59
Oh, ok didn't had this yet, as I do not use the `basic.enable.selectDataStructure` option.
Try to disable this and check again.

**Comment by ymauray** [comment] 2019-12-05 13:48
I'm not sure where to do that to be honest :-) 
I don't see that option anywhere except in ext_conf_template.txt 
`enable.selectDataStructure = 0`
Should I change it here ?

**Comment by ymauray** [comment] 2019-12-05 14:00
Also, now that I have selected the same DS for every localized version of my page, none of the content element show up on the page. I found that `tx_templavoilaplus_flex` is empty in the `pages` table. Maybe it's a side effect of the same problem ?

**Comment by opi99** [comment] 2019-12-05 16:18
Is there content in the Backend visible but not in Frontend or is it also missing in Backend?

**Comment by ymauray** [comment] 2019-12-06 09:01
Yes the content is visible in the backend, in all languages. Do you want me to setup an instance and give you access so you can check that out ? Or I can send you a tarball of said instance my the dump of the database.

**Comment by ymauray** [comment] 2019-12-06 09:44
Right, I've done a little digging.

Up to typo3 v8, the page data for the main language was stored in the `pages` table, and the translations for that page was stored in the `pages_language_overlay` table. So basically, you always got the same page, with all of its properties - including which template it used - and typo3 was, I belive, adding stuff from the language overlay.

Now in typo3 v9, the `pages_language_overlay` table doesn't exist anymore, and every version of the page is stored in the `pages` table. Which means TV's frontend controller gets the localized version's properties, which is, I believe, why every translated page needs to have its template set.

I will now try to understand why TV doesn't render any content element in the translated page, even with the template set. But I wouldn't be surprised if that change in Typo3 was the cause.

**Comment by opi99** [comment] 2019-12-06 10:08
As it seams to work for others and as I already did checks there, (yet) I don't get the point which is broken.
A tarball of any instance and dumps of database would make me happy here. :-) Maybe join the slack channel so we can exchange further details for this.

**Comment by ymauray** [comment] 2019-12-06 10:17
sure ! you can send me an invite to yannick.mauray@gmail.com

**Comment by ymauray** [comment] 2019-12-06 12:41
In the meantime, here's the procedure I've used. I've followed it twice, and each time I have the same result. 
https://gist.github.com/ymauray/820558ad238c09c1c154b31eab9dd4e7
Hope that helps !

**Comment by opi99** [comment] 2019-12-06 13:07
`Site management > Sites, edit site, add french language`
Do you still have sys_domain_languages and the static_country_info installed?

**Comment by ymauray** [comment] 2019-12-06 13:38
No. It's a brand new typo3 9.5.11 installed fresh from composer.

**Comment by opi99** [comment] 2019-12-06 14:45
Ahhh, ok, so you seam to have issue #223 which isn't solved yet ... till yet I've no customer who only use sites configuration.

**Comment by ymauray** [comment] 2019-12-09 10:32
Is there anything else I can do to help ?

**Comment by opi99** [comment] 2019-12-09 12:43
Hmmm, coding and send patches or paying hours. ;-)

**Comment by ymauray** [comment] 2019-12-10 08:01
I can have a look if you give me some pointers !

**Comment by opi99** [comment] 2019-12-10 08:18
Take a look inside `TemplaVoilaUtility::getAvailableLanguages()` and `getSysLanguageRows9` we need there a variant, which uses 
`        try {
            $site = GeneralUtility::makeInstance(SiteFinder::class)->getSiteByPageId($pageId);
        } catch (SiteNotFoundException $e) {
            $site = new NullSite();
        }

        // Fetch the current translations of this page, to only show the ones where there is a page translation
        $allLanguages = $site->getAvailableLanguages($this->getBackendUser(), false, $pageId);
`
See `typo3/sysext/backend/Classes/Controller/EditDocumentController.php::getLanguages()`

Maybe we should rename getAvailableLanguages in getAvailableLanguagesDeprecated and getAvailableLanguages9 (which gets the new code parts).

**Comment by ymauray** [comment] 2019-12-12 11:14
I will have a look first chance I get ! 
Also, it seems I need an invite link to join the slack channel. Or am I doing it wrong ?

**Comment by jpmschuler** [comment] 2019-12-13 11:45
> Also, it seems I need an invite link to join the slack channel. Or am I doing it wrong ?
You just need a typo3.org account: https://my.typo3.org/about-mytypo3org/slack

**Comment by opi99** [comment] 2020-02-21 11:56
I digged again into this issue and found out that the issue is a simple stupid one and haven't todo with my first thoughts on that. I pushed a fix for this into the 7.3.x branch, please test, so I could do another 7.3 release on monday.

**Closed** 2020-02-21 13:50 UTC
Labels: Bug
