### ISSUE TITLE
TV+ 8.x and Typo3 10?

### ISSUE THREAD

**Issue by baden32** [pluspol-interactive/templavoilaplus#293] opened 2021-05-26 10:32 UTC
Hello,
Would it be possible to get an update about the possible available date of TV+ 8?
I need to upgrade a couple of website to Typo3 10.4 but it's not possible at the moment.

I checked the issue (https://github.com/pluspol-interactive/templavoilaplus/issues/231) but in the end I cannot find more info about TV+ 8.x.

Thank you for your job and your next info.
Regards.
Joel

PS: I gladly help with French translations if needed. Are some info/files available to make this job?

**Comment by Outdoorsman** [comment] 2021-05-30 15:08
Hi @baden32, I posted about REALLY needing MySQL 8 support in Aug of 2020 since it's not supported till TYPO3 10. I had done my best to not bug anyone about it. However, I'm checking back here more and more often as my new hosting location only offers MySQL 8 so that means paying for an additional legacy hosting location to accommodate client sites that are using TV+ :(

[I did receive a reply](https://github.com/pluspol-interactive/templavoilaplus/issues/231#issuecomment-721426855) that it _I think_ that TYPO3 11 support is going to be rolled out at the same time once the new TV+ 8 version is released. I'm not sure at the rate that things are going if TV+ 8 will be out by the time TYPO3 12 comes out or not, but you can see that there are [consistent commits happening](https://github.com/pluspol-interactive/templavoilaplus/commits/master), even two of them yesterday.

**Comment by opi99** [comment] 2021-05-30 17:01
Hi,

I do my best, as I can, but such a complete rewrite is hard. Beside having full time job and 4 childs.
You can check out the slack channel where I try to show regularly what works.

**Comment by Outdoorsman** [comment] 2021-05-30 18:59
I didn't know about the Slack channel... will check that out. Thank you! Kids always come first... way to go.

**Comment by baden32** [comment] 2021-05-31 06:36
Hi,
Thank you for your replya and the info. Could you let me knw what "Slack channel" you're talking about? How to connect?

**Comment by opi99** [comment] 2021-05-31 08:05
More information about the TYPO3 Slack channels can be found here https://typo3.org/community/meet/how-to-use-slack-in-the-typo3-community
The TV+ Slack channel then is here: https://typo3.slack.com/messages/templavoilaplus

Will close this issue as duplicate of #231

**Closed by opi99** 2021-05-31 08:05 UTC

**Comment by baden32** [comment] 2021-05-31 10:17
Connected to The TV+ Slack channel thanks.
JZ

**Comment by ksjogo** [comment] 2021-05-31 22:34
In case you have client websites relying on TV, why not have them sponsor development?

**Comment by opi99** [comment] 2021-06-01 05:58
Sponsoring would be great.
Sponsor/Help coding, sponsor documenting.

**Comment by ksjogo** [comment] 2021-06-01 15:05
Which kind of budget/time left is your current estimate?

**Comment by opi99** [comment] 2021-06-01 18:32
Till yet I didn't think about an estimation, I could try to make a more "planable" plan. ;-)
As I'm a private person, I'm not familiar with all the sponsorship parts ... I tried to understand the GitHub Sponsor thing ... but I hate forms. :-(
But it could be possible to "buy development time" from Extrameile GmbH https://www.extrameile-gehen.de/ so if you (or others) like, contact me/us and we can work out a plan.

BTW:
The next part would be the backend editing modal, after that, the backend should work for "non language"/"non workspace" TYPO3 installations.
After that, integration with clipboard or multi-lang support could be next.
The Editor in the ControlCenter will get removed or better transfered into an another extension, so both can be released independently.

It would also be great to have someone helping with the "demo theme" https://github.com/extrameile/em_tvplus_theme_demo

**Comment by opi99** [comment] 2021-06-11 09:46
Version v8.0.0-alpha.7 got released.
I'm hoping for feedback.

**Comment by Outdoorsman** [comment] 2021-06-14 18:54
What do you guys typically do to spin up a quick test site to test things like this on since I don't have one that's not live at the moment?

**Comment by jpmschuler** [comment] 2021-06-15 07:23
@Outdoorsman You mean locally? Like using DDEV (a docker one-click-solution)? https://typo3.com/blog/tutorial-get-a-local-typo3-v10-installation-with-no-effort

**Comment by opi99** [comment] 2021-06-15 07:45
We use ddev for local development and robo scripts (in old installations deployer) to pull the state of live system to local machines (excluding personal data) with automatic generating of BE user.
