### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by heavykarl** [pluspol-interactive/templavoilaplus#68] opened 2017-05-22 05:35 UTC
With "Separate structures / 1:1" (langDisable = 0) as Page localization mode, the original language is not displayed.

**Comment by opi99** [comment] 2017-05-22 06:58
Hi, do you have a screenshot how it looked before? I'm a bit unsure.
Also which version of TV+ and TYPO3 do you use?

**Comment by heavykarl** [comment] 2017-05-22 07:24
![translation](https://cloud.githubusercontent.com/assets/24545391/26296730/42762688-3ed0-11e7-87ef-90556ed570a7.jpg)

Her eyou can see, that I have an extra page for each language, what "separate" means. my problem is, that the original language (0) is not displayed in the frontend, just the the translation (lang 1)

**Comment by opi99** [comment] 2017-05-22 08:33
That's how it looks on my System:
![screenshot_20170522_103027](https://cloud.githubusercontent.com/assets/1672061/26299096/dbbd0ba0-3ed9-11e7-8c50-c460ed5a20f8.png)

And FE works over all languages.
Does it works, if you set the Language parameter L=0 by hand?

**Comment by heavykarl** [comment] 2017-05-22 08:48
How come my translation panel looks completely different? I'm using the latest templavoilaplus version from the TER.

**Comment by opi99** [comment] 2017-05-22 09:16
Yes, looks differently (as language handling is not configured "separate", missed that point).
At the moment, I've no installation with "seperated" and I don't find how it had worked with page elements.
Anyway, could you please send the screenshot of the old installation, before updating to TV+?

**Comment by opi99** [comment] 2017-05-22 09:21
BTW: I think, if it can't found the lang=0, why should it take lang=1?
Is it possible that you set sys_language inside TypoScript wrongly? Which only get catched now as you Updated TYPO3 version?

**Comment by heavykarl** [comment] 2017-05-22 09:33
![unbenannt4](https://cloud.githubusercontent.com/assets/24545391/26301482/a8320f30-3ee1-11e7-89b6-2cf223287c86.PNG)

Here a screenshot of the old version, looks nearly the same. 

Here is one of my TS langugage setting:
![unbenannt5](https://cloud.githubusercontent.com/assets/24545391/26301739/56eca3e6-3ee2-11e7-846b-5518f087dae3.PNG)

And not to get anything wrong. It's just the content that is not rendered, the all around template is working in both langugages

**Comment by opi99** [comment] 2017-05-22 09:58
Ok, so the page title is lang=0 and the FCEs are lang=1?

**Comment by opi99** [comment] 2017-05-22 10:36
Anyway, I looked through the code pathes and all seams correct.

Can you debug a little bit?

In typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php Line 2774 (inside settingLanguage() function)
there is following code

```
} else {
    // fallback to the TypoScript option when rendering with sys_language_uid=0
    // also: use "en" by default
    if (!empty($this->config['config']['sys_language_isocode_default'])) {
        $this->sys_language_isocode = $this->config['config']['sys_language_isocode_default'];
    } else {
        $this->sys_language_isocode = $this->lang != 'default' ? $this->lang : 'en';
    }
}
```

Check which value `$this->sys_language_isocode` get (it should normally be 'de' for your lang=0 and 'en' for you lang=1).

**Comment by heavykarl** [comment] 2017-05-22 11:49
$this->sys_language_isocode is right, lang 0 it shows "de" and for lang 1 it shows "en".
disablelang in templates is 0 and in FCE 1. I also changed it in FCEs but there was no difference. I even do not get content if there is just a standard element in it, without any FCEs.

**Comment by opi99** [comment] 2017-05-22 12:06
Ok, so we need to debug inside templavoilaplus now.

In typo3conf/ext/templavoilaplus/Classes/Controller/FrontendController.php Line 345 (Function renderElement)

Code looks like:
```
$TOlocalProc = $singleSheet ? $TOproc['ROOT']['el'] : $TOproc['sheets'][$sheet]['ROOT']['el'];
// Store the original data values before the get processed.
$originalDataValues = $dataValues;
$this->processDataValues($dataValues, $dataStruct['ROOT']['el'], $TOlocalProc, $vKey, ($this->conf['renderUnmapped'] !== 'false' ? true : $TO['MappingInfo']['ROOT']['el']));
```
After this we need following output: `var_dump($lKey, $vKey);die();`
And send me the output.

**Comment by heavykarl** [comment] 2017-05-22 12:11
German: 'lDE', ENGLISH: 'lEN' -> l = small L

**Comment by opi99** [comment] 2017-05-22 12:14
Yes, but there should be 2 values per run.

**Comment by heavykarl** [comment] 2017-05-22 12:16
nope, just one.

**Comment by opi99** [comment] 2017-05-22 12:31
Oha, so our issue is between Line 337 and 344

```
$vKey = ($GLOBALS['TSFE']->sys_language_isocode && !$langDisabled && $langChildren) ? 'v' . strtoupper($GLOBALS['TSFE']->sys_language_isocode) : 'vDEF';

/* Hook to modify value key - e.g. used for EXT:languagevisibility */
foreach ($hookObjectsArr as $hookObj) {
    if (method_exists($hookObj, 'renderElement_preProcessValueKey')) {
        $vKey = $hookObj->renderElement_preProcessValueKey($row, $table, $vKey, $langDisabled, $langChildren, $this);
    }
}
```

But Line 337 should give us a minimum of "v" for the variable $vKey. So, do you have an extension which hooks into TV+?

Please check the values of $vKey after line 337 and after 344

**Comment by heavykarl** [comment] 2017-05-22 12:35
I'm not sure if there is an extension which hooks into TV+, what could it possibly be?
The Output shows no $vKey, neither on L337 or L344

**Comment by opi99** [comment] 2017-05-22 12:41
No value in $vKey after line 337? Strange. Any PHP Error/Notice in any log about that line?

**Comment by heavykarl** [comment] 2017-05-22 12:51
Both show "vDEF" (sorry, I made a mistake)

**Comment by opi99** [comment] 2017-05-22 12:59
Aaaahhhh :-)

But damn ... it seams I have the point. Need to check how it was in old 1.9 TV versions, this seams broken since longer.

**Comment by heavykarl** [comment] 2017-05-22 13:02
The Version was 1.9.7

**Comment by opi99** [comment] 2017-05-22 13:15
I mean, I need to check the source in TV 1.9 :-)
But no time today anymore, hopefully I get time tomorrow.

**Comment by heavykarl** [comment] 2017-05-22 13:36
Thank you, hopefully you will find the problem (and a solution)

**Comment by opi99** [comment] 2017-05-22 19:24
The problem is a change in TYPO3 core value of `$GLOBALS['TSFE']->sys_language_isocode`
Till 6.2 it is empty (and so false) if sys_language_uid is 0.
Since 7.x this var is always filled with the isocode also for sys_language_uid = 0.

If one uses langChildren, then $vKey gets "vISOCODE" instead of vDEF but it is no problem as this do not exists and so we get a fallback to vDEV.

But for langChildren=0, we have $lKey = "lISOCODE" instead of "lDEV" and this won't fallback so no content found and this leads to the problem here.

**Comment by opi99** [comment] 2017-05-22 22:49
Try to exchange your typo3conf/ext/templavoilaplus/Classes/Controller/FrontendController.php with this one and please tell me if it works.
[FrontendController.php.txt](https://github.com/pluspol-interactive/templavoilaplus/files/1020427/FrontendController.php.txt)

**Comment by heavykarl** [comment] 2017-05-23 08:01
It works, thank you very much!

**Comment by opi99** [comment] 2017-05-23 08:43
Thanks for feedback, will be in the 7.1.0 release which will be done in the next hours.

**Closed** 2017-05-23 08:42 UTC
Labels: Bug
