### ISSUE TITLE
v8: Section does not work

### ISSUE THREAD

**Issue by softwerft** [pluspol-interactive/templavoilaplus#109] opened 2017-08-18 09:44 UTC
If you create a section in TV+ it is unusable in creating FCE on page. When i try to create new section i get an 500 with error "#1478345642: Identifier could not be decoded to an array". (TYPO3 8.7.3)

**Comment by softwerft** [comment] 2017-08-18 10:45
Maybe the reason is that the $identifier is not empty. It is an string with 2 chars: '""'

**Comment by opi99** [comment] 2017-08-19 08:44
Did you try this eventually with TYPO3 v7 LTS?

**Comment by sytura** [comment] 2017-08-22 10:30
I can confirm this issue in 8.7.4 and templavoilaplus 7.1.3

I'm using a "Slider-FCE" with sections. If I try to add a new element I got a 500 error, too.

See attached screenshot:
http://screenshots.sytura.de/2017-08-22_12-20-17.png

I

**Comment by sytura** [comment] 2017-08-22 10:49
Same issue in TYPO3 8.7.4 and templavoilaplus 7.2 dev

**Comment by opi99** [comment] 2017-08-22 11:02
I asked if this happens with TYPO3 v7 LTS ... if you have time to test it there. :-)

**Comment by sytura** [comment] 2017-08-22 11:33
It works fine in TV 7.6.18 and templavoilaplus 7.1.0

No problems, whenn adding a new element. See:
http://screenshots.sytura.de/firefox_2017-08-22_13-27-04.png

No messages in firebug!

**Comment by opi99** [comment] 2017-08-22 14:12
Ok, thx for your help, so I only need to find out what is wrong in the Identifier in v8 LTS

**Comment by softwerft** [comment] 2017-08-22 14:27
Yes, i have the impression, that the data-datastructureidentifier attribute in the a should not be empty. 
![screenshot_20170822_161958](https://user-images.githubusercontent.com/10399835/29570273-49ec607a-8756-11e7-8091-1648a7fd437a.png)
This HTML will be generated in TYPO3\CMS\Backend\Form\Container\FlexFormSectionContainer

**Comment by opi99** [comment] 2017-09-06 20:19
It seams the base issue behind this is the same as #111

Can you please check if, with latest git, the fields from screenshot above are now filled correctly? (The issue itself isn't solved yet.)

**Comment by softwerft** [comment] 2017-09-07 11:17
It look like nothing changed.

**Comment by opi99** [comment] 2017-09-07 12:00
So the attribute "data-datastructureidentifier" isn't set with latest git master?

**Comment by softwerft** [comment] 2017-09-07 15:18
exactly

**Comment by Outdoorsman** [comment] 2017-10-09 17:36
**It looks like I'm experiencing this issue as well. Following are the steps to reproduce.**

I created a flexible content element structured as follows...
![2017-10-08_18-03-55](https://user-images.githubusercontent.com/3075533/31350702-0d58569e-acdd-11e7-850e-93f9f832259b.png)
...but I can't add any of the repeating CO's in the backend! I click the plus (following picture) to add a new repeating element and and nothing happens.
![2017-10-08_18-04-53](https://user-images.githubusercontent.com/3075533/31350701-0d52100e-acdd-11e7-8f59-25d11258e12b.png)
The HTML that generates that plus icon to click is as follows...
```<div class="t3-form-field-add-flexsection">
  <div class="btn-group">
    <a href="#" class="btn btn-default t3js-flex-container-add" data-vanillauid="1124" data-databaserowuid="1124" data-command="edit" data-tablename="tt_content" data-fieldname="tx_templavoilaplus_flex" data-recordtypevalue="templavoilaplus_pi1" data-datastructureidentifier="" data-flexformsheetname="sDEF" data-flexformfieldname="field_class" data-flexformcontainername="field_class_el">
    <span class="t3js-icon icon icon-size-small icon-state-default icon-actions-document-new" data-identifier="actions-document-new">
      <span class="icon-markup">
      <img src="/typo3/sysext/core/Resources/Public/Icons/T3Icons/actions/actions-document-new.svg" width="16" height="16">
      </span>
    </span>
    </a>
  </div>
</div>```

**Comment by softwerft** [comment] 2017-10-10 08:22
yes, that is exactly this issue. I am still fixing it.

**Comment by rareshluk** [comment] 2017-10-13 09:10
Any ETA on when this will be fixed? ... approximately

**Comment by softwerft** [comment] 2017-10-13 09:55
i fixed it, but first want to test. Maybe on monday.

**Comment by Outdoorsman** [comment] 2017-10-13 15:45
@softwerft thanks so much for the update. I have a client that I was supposed to have release a website for but can't until this is resolved. So having a timeline is very helpful to know. Looking forward to Monday very much.

**Comment by Outdoorsman** [comment] 2017-10-15 23:38
@softwerft Being it's Monday, please let me know if need someone to test for you if that's what's holding things up.

**Comment by softwerft** [comment] 2017-10-16 15:27
@Outdoorsman i am ready. Now i prepare the pull request.

**Comment by opi99** [comment] 2017-10-17 09:14
First look into it ... thats not the solution, but it gives me a hint where to look deeper.

1) It may solve the issue for Sections in nun multi lang flexforms
2) FlexFormElementContainer shouldn't call DataBase (BTW. it is only v8+ compatible)

**Comment by softwerft** [comment] 2017-10-17 09:49
@opi99 thanks for look into. In 8.7.7 it works fine. 
1. Could be. We do not need multilang there.
2. We need the flexFormDataStructureIdentifier in FlexFormElementContainer to generate the Add-Container-Button, so i decide to use FlexFormTools->getDataStructureIdentifier and for that method i need the database-row. First i solved it with xclass-ing the FormFlexAjaxController and do the same there (generate the flexFormDataStructureIdentifier), but i think it is always better to reduce the xclasses, right?

**Comment by softwerft** [comment] 2017-10-17 09:50
@Outdoorsman Does the fix work in your installation?

**Comment by opi99** [comment] 2017-10-17 09:54
We need to XClass FormFlexAjaxController anyway to get MultiLang to work. :)

**Comment by softwerft** [comment] 2017-10-17 09:56
If you like, i can commit my fix with the FormFlexAjaxController xclass..!?

**Comment by opi99** [comment] 2017-10-17 10:02
Yes post it as another pull request ... but it seams I won't have time this week to check deeper.

**Comment by softwerft** [comment] 2017-10-17 12:09
Ok, then i will wait until you have more time.

**Comment by hidufy** [comment] 2017-11-11 14:17
Hello everybody,

I have the same problem. Is there a solution or a workaround?

Best regards
Michael

**Comment by Outdoorsman** [comment] 2017-11-12 17:41
Yes @softwerft the solution did work perfectly as far as I can tell in my installation. Sorry I didn't see your question till now.

**Comment by Outdoorsman** [comment] 2017-11-12 17:42
@hidufy yes there is already a solution that is being worked on. No sure what the hold-up has been other than busy people. I expect it should be publish very soon though (crossing fingers).

**Comment by hidufy** [comment] 2017-11-12 17:48
Thank you for the feedback. Then I'll keep my fingers crossed, too.

**Comment by Outdoorsman** [comment] 2017-11-12 17:58
Yes, me too!

**Comment by Outdoorsman** [comment] 2017-11-13 01:18
Hmmm... I have another TYPO3 installation that I'm using that patch @opi99 shared with me and am having issues but am not certain it is related to this extension... what do guys you think?

1. Be logged in as a non-admin user
2. Change one of the Flexible Content Element fields and try to save the content element
3. The change is ignored

But when I change the user to admin privileges it saves fine. Don't know if it's related at all but I checked the TYPO3 logs and see this...

```Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1478113873: Incomplete "record" based identifier: {"type":"record","tableName":"tt_content","uid":0,"fieldName":"tx_templavoilaplus_ds"} | RuntimeException thrown in file /some_directory/typo3_src-8.7.8/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php in line 644. Requested URL: http://www.example.com/typo3/index.php?M=web_txtemplavoilaplusLayout&moduleToken=d487481297b0611a09f2bdf4d8699b6d6df60a02&id=4&altRoot=&versionId=&CB%5BremoveAll%5D=normal&pasteRecord=copy&source=tt_content%3A115&destination=pages%3A4%3AsDEF%3AlDEF%3Afield_content%3AvDEF%3A5&returnUrl=%2Ftypo3%2Findex.php%3FM%3Dweb_txtemplavoilaplusLayout%26moduleToken%3Dd487481297b0611a09f2bdf4d8699b6d6df60a02%26id%3D4```

And here's an visual of the error...

![2017-11-12_16-43-07](https://user-images.githubusercontent.com/3075533/32705863-709905fe-c7cd-11e7-8f58-f7cf171cbdb3.png)

**Comment by rareshluk** [comment] 2017-11-13 09:21
I'm getting the same error on elements with inline contents

**Comment by hidufy** [comment] 2017-11-21 13:58
Hello everybody,

Can you give me an approximate time frame until when the error is resolved. I have created a website that is about to start, but there are still a few templates and content missing to insert.

If it takes too long I have to think of a plan B.


Best regards
Michael

**Comment by opi99** [comment] 2017-11-23 10:15
@hidufy Do you have Multi or Single language elements?

**Comment by hidufy** [comment] 2017-11-23 10:20
Only Single language elements.

**Comment by rareshluk** [comment] 2017-11-23 10:21
The issue I had, #146 , is on a multi language element

**Comment by opi99** [comment] 2017-11-23 10:30
@hidufy On Single language elements it seams the patch from softwerft is sufficient. Fot multi language it is not sufficient, that's why this issue is not fixed yet.

**Comment by rareshluk** [comment] 2017-12-14 09:42
Hi guys,
Any news on a fix for this issue with multi language elements?

**Comment by rareshluk** [comment] 2018-02-09 08:49
@opi99 I will be able to test it next week on multi language elements, on TYPO3 8.7.8

**Comment by rareshluk** [comment] 2018-02-12 11:47
Hi guys,
I've tested the new patched version, 7.2.2.-dev on TYPO3 8.7.8 and I still get the 
Incomplete "record" based identifier error
![copy_error](https://user-images.githubusercontent.com/13641074/36095287-d96c815c-0ff1-11e8-9d90-52c5d2ffef78.png)
Also, the https://github.com/pluspol-interactive/templavoilaplus/issues/109 issue is back, meaning, I can't create new inline elements again, - in console it returns the 500 server error again, like it did before.

**Comment by rareshluk** [comment] 2018-02-12 13:13
a bit more info:
- the error above occurs when copy/paste-ing any page (with/without a TV element on it) - so I noticed that this error occurs when in the Page properties > Appearance, the Page Template Structure and/or Subpages - Page Template Structure are populated.
![page_subpage_ts_td](https://user-images.githubusercontent.com/13641074/36098315-c9c65414-0ffe-11e8-8171-15e19a8db182.png)
If I leave those fields empty - the copy/paste of the page works, but of course, the layout in the frontend is then wrong

**Comment by opi99** [comment] 2018-02-12 13:37
@rareshluk TemplaVoilà! is a big extension, so it is in need to be very precise about what happens.
Only telling me, that something happens without writing what are you doing doesn't help much.

So please write detailed, what are you doing to get your first issue (The "Incomplete "record" based identifier error" which seams is another issue then this patch will solve). And also what are you doing to get the second error ... and as this patch is about sections and not IRRE you hit another issue.
I also do not understand what means "is back" in relation to what? To the 7.2.1 release? Or to the patch from softwerft in issue 109?

**Comment by rareshluk** [comment] 2018-02-12 14:06
@opi99 I know it's a big extension, and I would like to thank you all for developing it and making it available. I'm willing to help with whatever I can.
The scenario is rather simple. I have a TYPO3 ver. 8.7.8 website, with some Page templates, and a series of FCEs.
Let's say I have a page, for which I select Page Template Structure "Main", and Template Design "Main", then I select the TS and TD for its subpages "Subpage".
When I then try to copy this page and paste it below the original one, I get the "Incomplete "record" based identifier error". If I leave the TS and TD fields empty for both current page and subpages, I'm able to successfully copy the page.
The same happens with any page that has a FCE on it where a Template Object is selected under "Appearance".
When I said "is back", i was referring to the issue that was fixed by the patch from softwerft in issue 109

**Comment by opi99** [comment] 2018-02-12 14:18
Ok, will try issue 1 from you and create a new issue report about that, as it hasn't todo with this one.

For issue 2, do you speak about sections or IRRE and if, how is it configured in the DataStructure?

**Comment by rareshluk** [comment] 2018-02-12 14:27
See the DS file i uploaded here https://github.com/pluspol-interactive/templavoilaplus/issues/146#issuecomment-344519728

**Comment by opi99** [comment] 2018-02-12 14:28
I moved issue 1 in #160

**Comment by opi99** [comment] 2018-02-12 14:44
Tested your 2nd issue locally with this patch here activated.
It works for me, you have 2 Containers in a section, which I never tested, but it works like a charm  (tested on TYPO3 8.7.10)

So, my question, did you clear all TYPO3 caches, after checking out this patch?

**Comment by rareshluk** [comment] 2018-02-12 14:49
Yes, I'm clearing all caches including PHP opcache in install tool, and I also re-created the autoload information for extensions

**Comment by opi99** [comment] 2018-02-12 14:57
So I can't reproduce your issue.
While you are getting the 500 error, what is the response text of that request?

**Comment by rareshluk** [comment] 2018-02-12 15:29
Hi opi99,
I am not getting the error anymore (no idea why ... all I did was to bring in the 7.2.2 version again, and patch it with the patch from Friday - just like i did before)
And I am getting no 500 error anymore, but when adding a new item the element disappears from the front-end, and I'm getting a error "Oops, an error occurred! Code: 20180212162450656db967"
in the backend log I only see warnings "Core: Error handler (FE): PHP Warning: Illegal string offset 'el' in /httpdocs/typo3conf/ext/templavoilaplus/Classes/Controller/FrontendController.php line 563"

**Comment by opi99** [comment] 2018-02-12 16:20
So adding elements in Backend works with this patch?

**Comment by rareshluk** [comment] 2018-02-12 16:23
Yes, it works now.
Just i think smth goes wrong when saving. I didn't have time today, but
tomorrow I will compare the result after saving, both with 7.2.0 and
7.2.2-dev
And see if I spot a difference.

Am 12.02.2018 17:20 schrieb "Alexander Opitz" <notifications@github.com>:

**Comment by opi99** [comment] 2018-02-15 09:14
@rareshluk Did you find anything?

**Comment by rareshluk** [comment] 2018-02-15 10:10
@opi99 No, I didn't spot any difference in the table record.

But: I've got both templavoilaplus 7.2.0 and 7.2.2-dev in typo3conf, and simply switching between the 7.2.0 and 7.2.2-dev, without saving the record, clearing all caches, and refreshing the frontend, makes the content element show up on 7.2.0, and disappear and display the error I mentioned above on 7.2.2-dev

I'm still digging to see if I can find where it actually crashes

**Comment by opi99** [comment] 2018-02-15 15:30
The patch do not change the frontend output functionality, it's all about backend editing.

**Comment by Neowar** [comment] 2018-02-16 12:50
Hello,

Due to the upgrade to TYPO3 8.7.9, we made the change from templavoila to templavoilaplus and had the same problem as described above.

The patch will now work to create new section elements, but in the front end we will not see anything. Neither the existing elements nor the new ones.

According to our search in the code, this new bug is definitely triggered by the patch.

Previously, the new Section elements were stored in the database with the following XML:
`<section index = "1">
    <itemType index = "field_do_partner">
        <El>
            <field index = "field_image">
                <value index = "vDEF"> image.png </ value>
            </ Field>
            <field index = "field_subtext">
                <value index = "vDEF"> subtext </ value>
            </ Field>
            <field index = "field_image_link">
                <value index = "vDEF"> www.google.com _blank </ value>
            </ Field>
        </ El>
    </ ItemType>
    <itemType index = "_ TOGGLE"> 1 </ itemType>
</ Section>
`

After the patch, new elements are now created as XML as follows:

`<field index = "5a85ba0323924869753297">
    <value index = "field_do_partner">
        <El>
            <field index = "field_image">
                <value index = "vDEF"> image.jpg </ value>
            </ Field>
            <field index = "field_subtext">
                <value index = "vDEF"> subtext </ value>
            </ Field>
            <field index = "field_image_link">
                <value index = "vDEF"> http://www.google.com _blank </ value>
            </ Field>
        </ El>
    </ Value>
    <value index = "_ TOGGLE"> 1 </ value>
</ Field>
`

Note here the first opening tag. It is striking that the Section Element is no longer stored as a section but as a field and that the index is no longer integer, but corresponds to a hash.

And this is exactly the problem for the frontend output. In the file Classes/Domain/Model/HtmlMarkup.php in line 604 to 607 it is checked if the structure is a section.

`
if (is_array($editStruct) && count($editStruct)) {
	$testInt = implode('', array_keys ($editStruct));
	$isSection =! preg_match('/ [^ 0-9] /', $testInt);
}
`

The check works for the old section elements in the XML without problems because the index is a number. It does not work anymore on the new ones because the index is now a hash. This will not execute the following code ( if ($isSection) ).

The new hash is created in the new file Classes/Form/Controller/FormFlexAjaxController.php (which was added by the patch) in line 66:

`
$flexFormContainerIdentifier = StringUtility::getUniqueId();
`

So the bug definitely comes through the patch. We hope it can be fixed. Because our customer is unfortunately dependent on the functionality with Templavoilaplus.

Greeting Kay

**Comment by opi99** [comment] 2018-02-16 13:04
Thanks for the deep insight feedback ... that helps me a lot to identify the issue.

I understand till 7 LTS this index number was generated by the JS, as it gets a complete empty entry attached, which will then be copied.
Since 8 this is done by an Ajax call, which do not know how much elements where already added.

I will look if we can handle this change in FE output or if we need the index to be a number.

**Comment by opi99** [comment] 2018-02-16 13:05
.oO( My test got an UniqueID which is integer *wow* )

**Comment by opi99** [comment] 2018-02-16 13:57
So, I looked into the false element in frontend, so I didn't saw this problem. Hopefully this commited patch will work for you.

**Comment by Neowar** [comment] 2018-02-16 14:58
Thanks for the quick bugfix. However, a small mistake still is inside. In the file HtmlMarkup.php in line 604:

Current: if (is_array ($editStruct) && isset ($editStruct ['_SECTION']) && $editStruct ['_SECTION'] === true) {

Correctly: if (is_array ($editStruct) && isset ($editStruct ['__ SECTION']) && $editStruct ['__ SECTION'] === true) {

And in line 619 this has to go var_dump again out. ;-)

Then it is also correctly output in the Frontend (old and new elements).

Kay

**Comment by rareshluk** [comment] 2018-02-16 15:08
I can confirm too.
This patch displays both old and new elements in Frontend
Great job, guys!

**Comment by opi99** [comment] 2018-02-16 15:39
Ok, yes, changed this in both files but commited it wrong. :-/

**Closed** 2018-03-01 19:12 UTC
Labels: Bug

**Comment by woodyc79** [comment] 2019-01-14 13:02
Hello! We've got the same issue still here in TYPO3 8.7.22 and TVPlus 7.3.0... I get e 500error 	

Oops, an error occurred!
Identifier could not be decoded to an array.
More information regarding this error might be available here (https://wiki.typo3.org/Exception/CMS/1478345642)

I thought that has been fixed?

Kind regards,
Christian

**Comment by opi99** [comment] 2019-01-14 13:35
This error number indicates an other issue. So more information is needed. When and where does this happen and so on ... but please open another issue report for this.

**Comment by opi99** [comment] 2019-01-14 13:36
Or maybe you didn't run the migration scripts.

**Comment by woodyc79** [comment] 2019-01-15 07:22
> This error number indicates an other issue. So more information is needed. When and where does this happen and so on ... but please open another issue report for this.

It is not another issue or error => Number 1478345642 is the error number the thread-started (softwerft) provided ;-)
