### ISSUE TITLE
non-admin-BEuser can't modify sites and content

### ISSUE THREAD

**Issue by sportsocke** [pluspol-interactive/templavoilaplus#265] opened 2019-11-26 17:40 UTC
Hi

I have updated a project from TYPO3 6.2 with old templavoila to TYPO3 9.5.11 with newest templavoilaplus.... Now, the normal BEusers can't modify pages and content. He got a error message that he has no permission if he want to edit the page.
If he want to insert content he got no error message, but the content went in to the "non used elements" tab.

Tried to give the editor every single right of the "tables", "pages" and "content" accessrights... no effect. He still seems to have no rights.

If I deactivate templavoilaplus everything is fine.. user can change pages and content.

<img width="1243" alt="Bildschirmfoto 2019-11-26 um 18 06 08" src="https://user-images.githubusercontent.com/49714627/69658021-b14f2f80-107b-11ea-8e2d-8584ffc98c3b.png">

<img width="1103" alt="Bildschirmfoto 2019-11-26 um 18 06 16" src="https://user-images.githubusercontent.com/49714627/69658024-b14f2f80-107b-11ea-890f-ed317cf6372d.png">

<img width="1480" alt="Bildschirmfoto 2019-11-26 um 18 39 10" src="https://user-images.githubusercontent.com/49714627/69658216-10ad3f80-107c-11ea-8755-7e0728c3d56c.png">

**Comment by sportsocke** [comment] 2019-11-26 17:43
Problem is with all existing pages and with new pages (made by the user himself)

**Comment by opi99** [comment] 2019-11-27 10:10
Hi could you try the latest source from the 7.3.x branch?
It sounds like a duplicate of issue #261 which is fixed there.

**Comment by sportsocke** [comment] 2019-11-27 10:14
I'm using 7.3.1  .. tried the github version too - but got two backend moduls with that one (2x sites, 2x templavoila)

**Comment by opi99** [comment] 2019-11-27 10:17
Do not use the master branch, use the 7.3.x branch please.

**Comment by sportsocke** [comment] 2019-11-27 10:18
I'm using the 7.3.1 version.. I have the problems with that one.

**Comment by sportsocke** [comment] 2019-11-27 10:18
<img width="1467" alt="Bildschirmfoto 2019-11-27 um 11 18 23" src="https://user-images.githubusercontent.com/49714627/69714948-af32b280-1107-11ea-9274-2b2bfe2daa50.png">
<img width="1284" alt="Bildschirmfoto 2019-11-27 um 11 18 41" src="https://user-images.githubusercontent.com/49714627/69714949-af32b280-1107-11ea-8b22-4c598b6282ae.png">

**Comment by opi99** [comment] 2019-11-27 10:22
PLEASE Test with the git 7.3.x BRANCH!

**Comment by sportsocke** [comment] 2019-11-27 10:27
sorry, bad question.. how can I get that? .. i'm downloading it as zip and installing it in the backend by myself

**Comment by opi99** [comment] 2019-11-27 10:30
Goto https://github.com/pluspol-interactive/templavoilaplus/tree/7.3.x and download as zip (This way it should work IMHO) or use git commands.

**Comment by opi99** [comment] 2019-11-27 10:31
Oh, it seams https://github.com/pluspol-interactive/templavoilaplus/archive/7.3.x.zip should be the link to the zip.

**Comment by sportsocke** [comment] 2019-11-27 10:43
Worked with that one... Great, thanks for your help.
The version 7.3.1 in the TER is wrong then?

**Comment by opi99** [comment] 2019-11-27 10:47
No, this isn't wrong, but after fixing this issue there was no release yet. Hopefully this will be done till x-mas.

**Comment by sportsocke** [comment] 2019-11-27 10:48
thanks a lot !!!!!!!! 

Best regards

**Closed by opi99** 2019-11-27 10:47 UTC
Labels: Question
