### ISSUE TITLE
Adding content element on alternative language problem

### ISSUE THREAD

**Issue by agendartobias** [pluspol-interactive/templavoilaplus#246] opened 2019-04-26 08:24 UTC
TYPO3 9.5.5
templavoilaplus 7.3.1 or 7.3.0 
PHP 7.2

Hey, when i want to add a content element (header,text,plugin - it doesn't matter) on translated page (alternative language id=1) the content element is not addad in page section "tx_templavoilaplus_flex". I must add it manualy -> Edit alternative lang page -> General -> scroll down to Content:[tx_templavoilaplus_flex] -> Content, and there i must find and select that record.

**Comment by mz-aimcom** [comment] 2019-04-30 13:21
I can confirm this issue for TYPO3 9.5.5 and TV+ 7.3.0.1.

**Comment by opi99** [comment] 2020-02-16 14:08
Question to this issue, how do you manage your languages?
With SideConfiguration or the old way with sys_languages?

**Comment by mz-aimcom** [comment] 2020-02-17 08:25
> Hey, i am using SitesConfiguration

Me too. I'm also using Site Configuration.

**Comment by opi99** [comment] 2020-02-17 08:48
So this issue depends on #223 and #266

**Comment by opi99** [comment] 2020-02-21 11:56
I digged again into this issue and found out that the issue is a simple stupid one and haven't todo with my first thoughts on that. I pushed a fix for this into the 7.3.x branch, please test, so I could do another 7.3 release on monday.

**Comment by agendartobias** [comment] 2020-02-21 13:03
It works! TNX

**Comment by opi99** [comment] 2020-02-21 13:45
Thanks for feedback

**Closed** 2020-02-21 13:51 UTC
Labels: Bug
