### ISSUE TITLE
update reference index

### ISSUE THREAD

**Issue by frodocat** [pluspol-interactive/templavoilaplus#179] opened 2018-05-30 10:49 UTC
If I install templavoilaplus on typo3 8.7.15 the typo3 "DB Check" -> "update reference index" is not working anymore.
The error:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1478106090: Parse error: Data structure could not be resolved to a valid structure. | TYPO3\CMS\Core\Configuration\FlexForm\Exception\InvalidIdentifierException thrown in file ****/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php in line 719. Requested URL: *****/index.php?M=system_dbint&moduleToken=--AnonymizedToken-- 

When I deinstall the extension the refence index is working again.

**Comment by opi99** [comment] 2018-05-31 08:00
Is this a complete new installation or is this a system which used TemplaVoilà already?

**Comment by frodocat** [comment] 2018-05-31 08:02
This is a system which used TemplaVoila already

**Comment by opi99** [comment] 2018-05-31 08:03
Did you run all TV+ Updates after installing the Extension?

**Comment by frodocat** [comment] 2018-05-31 08:05
Yes, I have version 7.2.1  and execute the upgrade script

**Comment by frodocat** [comment] 2018-05-31 08:06
templavoilaplus is working but my update reference index is not

**Comment by opi99** [comment] 2018-05-31 08:17
Hmmm, after the Upgrade Scripts from TemplaVoilà Plus all FlexForms should be readable.
Will check something, but maybe I need more information from you. To get the point which fails while reading FlexForms.
Can you debug?

**Comment by frodocat** [comment] 2018-06-04 13:02
Yes, I can send you the debug code. Can I mail it to you?

**Comment by opi99** [comment] 2018-06-19 12:37
So, excuse the long time.
I couldn't reproduce this issue, but it may happen through wrong assumptions on my side.
Can you edit the */typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php file around line 719 and add a var_dump($dataStructure) inside the if block before the exception?
* Is the output an empty string?
* Is it a string with value? Then whats the value?
* If it is no string, what is it then?

Thanks for help.

**Comment by frodocat** [comment] 2018-06-20 13:10
Hi Alexander,
    
    I am happy that you can help me. The output  is: bool(false)
    
    
    
    Alexander Opitz wrote:
    
    
      So, excuse the long time.
        I couldn't reproduce this issue, but it may happen through wrong
        assumptions on my side.
        Can you edit the
        */typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php
        file around line 719 and add a var_dump($dataStructure) inside
        the if block before the exception?
      
        Is the output an empty string?
        Is it a string with value? Then whats the value?
        If it is no string, what is it then?
      
      Thanks for help.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-398383784","url":"https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-398383784","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pluspol-interactive/templavoilaplus","title":"pluspol-interactive/templavoilaplus","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pluspol-interactive/templavoilaplus"}},"updates":{"snippets":[{"icon":"PERSON","message":"@opi99 in #179: So, excuse the long time.\r\nI couldn't reproduce this issue, but it may happen through wrong assumptions on my side.\r\nCan you edit the */typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php file around line 719 and add a var_dump($dataStructure) inside the if block before the exception?\r\n* Is the output an empty string?\r\n* Is 
it a string with value? Then whats the value?\r\n* If it is no string, what is it then?\r\n\r\nThanks for help."}],"action":{"name":"View Issue","url":"https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-398383784"}}}
      {
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [pluspol-interactive/templavoilaplus] update reference index (#179)",
"sections": [
{
"text": "",
"activityTitle": "**Alexander Opitz**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@opi99",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"pluspol-interactive/templavoilaplus\",\n\"issueId\": 179,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"pluspol-interactive/templavoilaplus\",\n\"issueId\": 179\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-398383784"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340535618\n}"
}
],
"themeColor": "26292E"
}

**Comment by opi99** [comment] 2018-06-20 17:17
Can you try to debug the lines above, I need to know, which part sets the $dataStructure to false.
Do you have DataStructures inside Database or as StaticDataStructure in files?

**Comment by opi99** [comment] 2018-06-27 09:59
Hi,

I found out that some migration wizards do not run (see #187) ... will fix this in the next minutes in git, you may rerun this migration wizards and try again if this error still occurs.

**Comment by frodocat** [comment] 2018-06-27 12:40
Hi Alexander,
    
    I updated templavoilaplus and it solved the problem with the manage
    reference index. Thanks for you help :-)
    mw. A.E. (Ardi) Nonhebel

ICT specialist  | 4TU.Centre for Research Data | TU Delft Library, Research Data Services 

T +31 (0)15 27 88 151 | E a.e.nonhebel@tudelft.nl 
T +31 (0)15 27 88 600 | E researchdata@4tu.nl | W http://researchdata.4tu.nl

Aanwezig: ma middag, di, wo, do, vr ochtend
    Alexander Opitz wrote:
    
    
      
      Hi,
      I found out that some migration wizards do not run (see #187)
        ... will fix this in the next minutes in git, you may rerun this
        migration wizards and try again if this error still occurs.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pluspol-interactive/templavoilaplus","title":"pluspol-interactive/templavoilaplus","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/pluspol-interactive/templavoilaplus"}},"updates":{"snippets":[{"icon":"PERSON","message":"@opi99 in #179: Hi,\r\n\r\nI found out that some migration wizards do not run (see #187) ... will fix this in the next minutes in git, you may rerun this migration wizards and try again if this error still occurs."}],"action":{"name":"View Issue","url":"https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-400615057"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-400615057",
"url": "https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-400615057",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [pluspol-interactive/templavoilaplus] update reference index (#179)",
"sections": [
{
"text": "",
"activityTitle": "**Alexander Opitz**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@opi99",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"pluspol-interactive/templavoilaplus\",\n\"issueId\": 179,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"pluspol-interactive/templavoilaplus\",\n\"issueId\": 179\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/pluspol-interactive/templavoilaplus/issues/179#issuecomment-400615057"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340535618\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by opi99** [comment] 2018-06-27 13:05
Thanks for your feedback, fix will be released with 7.2.4

**Closed by opi99** 2018-06-27 13:05 UTC
