### ISSUE TITLE
Not possible to mapping the template from filelist 

### ISSUE THREAD

**Issue by TYPO3plusi** [pluspol-interactive/templavoilaplus#131] opened 2017-09-27 19:59 UTC
In 7.6.x it works, in 8.7.x not.

**Comment by opi99** [comment] 2017-09-27 21:37
Can you add a screenshot of 7.6 where it works?

**Comment by TYPO3plusi** [comment] 2017-09-28 06:35
Sure, here is a screenshot:
https://imgur.com/a/MKhNj

**Comment by opi99** [comment] 2017-09-28 06:57
Ok, thx, then I'll close this issue as duplicate of #75

**Closed by opi99** 2017-09-28 06:57 UTC
Labels: Duplicate
